name: NanoPi-R2S Test Package
on:
  push:
    paths:
      - '.github/workflows/test-df.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test Environment
        run: |
          sudo df
          sudo pwd
          sudo du -d 5 -BM
          sudo df
          mkdir NanoTest2
          cd NanoTest2
          sudo pwd
          sudo df
          cd /
          sudo du -d 5 -BM
          sudo df
