name: NanoPi-R2S Test Package
on:
  push:
    paths:
      - '.github/workflows/test-df.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test Environment
        run: |
          sudo df
          sudo pwd
          sudo du -d 3 -BM
          sudo df
          sudo mkdir NanoTest
          sudo cd NanoTest
          sudo pwd
          sudo df
          cd /
          sudo du -BM
          sudo df
  
