name: NanoPi-R2S Test Package
on:
  push:
    paths:
      - '.github/workflows/test-df.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test Environment
        run: |
          sudo df
          sudo pwd
          sudo du -d 2 -BM
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo df
          mkdir NanoTest2
          cd NanoTest2
          sudo pwd
          sudo df
          cd /
          sudo du -d 2 -BM
          sudo df
